version: "3"

services: 
    app:
        # build:
        #     context: ./node
        image: leohck/codeeducation2-node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        command: node index.js
        tty: true
        volumes: 
            - ./node:/usr/src/app
        depends_on: 
            - db
        expose: 
            - 3000
        networks: 
            - challenge-network

    db:
        # build:
        #     context: ./mysql
        image: leohck/codeeducation2-mysql
        # command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        # environment: 
        #     - MYSQL_DATABASE=nodedb
        #     - MYSQL_ROOT_PASSWORD=root
        networks: 
            - challenge-network

    server:
        # build: 
        #     context: 
        #         ./nginx
        image: leohck/codeeducation2-nginx
        container_name: nginx
        ports:
            - "8080:80"
        networks: 
            - challenge-network
    
networks: 
    challenge-network:
        driver: bridge